# Generated by Django 5.2.4 on 2025-08-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=250)),
                ('note_detail', models.TextField(max_length=1000)),
                ('created_by', models.CharField(max_length=50)),
                ('note_date', models.DateField()),
                ('note_time', models.TimeField()),
            ],
        ),
    ]
