# Generated by Django 5.2.4 on 2025-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug_link',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
