# Generated by Django 5.2.4 on 2025-08-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_slug_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug_link',
            field=models.SlugField(null=True),
        ),
    ]
